/*
    Cerne Compiler - const mnemonic blueprint for node construction

    Copyright (c) 2026 Cerne Project
    SPDX-License-Identifier: LGPL-3.0-only

    This file is part of the Cerne Compiler.
    See the LICENSE file in the root directory for further details.
*/
#include "../../../include/parser/handler.hpp"

/**
 * returns whether there were errors or not
 */
bool parse_condition(const cerne::blueprint_arguments& args, std::unique_ptr<cerne::ConditionBlock>& condition_block, bool expect_expr) {
    auto& machine = args.machine;

    machine->advance(); // advance past the mnemonic token

    std::unique_ptr<cerne::Node> expr = nullptr;
    if(expect_expr) {
        expr = machine->parse_expr(0);
        if(!expr) {
            cerne::cerror(
                machine->file_path,
                ERR_UNEXPECTED_SYMBOL,
                std::format("Unexpected token `{}` at {}:{}", *(machine->peek().value), machine->peek().span.line, machine->peek().span.col),
                cerne::code_snippet(machine->code_sv, machine->peek().span, std::format("Expected expression, but found `{}`", *(machine->peek().value))),
                machine->peek().span
            );
            machine->errors++;
            return false;
        }
    }

    // parse the scope after the initial part of the statement (mnemonic + expression or just mnemonic if it's an else statement)
    auto scope = machine->parse_scope();
    if(!scope) {
        cerne::cerror(
            machine->file_path,
            ERR_UNEXPECTED_SYMBOL,
            std::format("Unexpected token `{}` at {}:{}", *(machine->peek().value), machine->peek().span.line, machine->peek().span.col),
            cerne::code_snippet(machine->code_sv, machine->peek().span, std::format("Expected scope, but found `{}`", *(machine->peek().value))),
            machine->peek().span
        );
        machine->errors++;
        return false;
    }

    // if, elif vs else
    if(expect_expr) {
        // make condition pair and add it to the condition block
        auto condition = std::make_pair(std::move(expr), std::move(scope));
        condition_block->conditions.push_back(std::move(condition));
    } else {
        // else statement goes to it's specific property on the block
        condition_block->else_block = std::move(scope);
    }

    machine->advance(); // advance past the scope token
    return true;
}

/**
 * sets should_end to true when there is a problem with the statement(s)
 */
void mnemonic_cases(const cerne::blueprint_arguments& args, std::unique_ptr<cerne::ConditionBlock>& condition_block, bool* should_end, cerne::Token& mnemonic) {
    if(*(mnemonic.value) == "elif") {
        auto new_condition = parse_condition(args, condition_block, true);
        if(!new_condition) *should_end = false;
        else return; // if we successfully parsed the elif, we return to continue the loop
    } else if(*(mnemonic.value) == "else") {
        parse_condition(args, condition_block, false);
        *should_end = true; // we set should_end to true because else is the last condition, and we don't want to continue the loop
    } 
    
    // any other case is considered valid to break out of the conditional block loop
    *should_end=false;
}

/**
 * a condition block has to begin with an if statement
 * once the if statement is triggered, the first condition is created (with the expression generated by parse_expr(0) and the scope)
 * we check for the token after the scope, if it's an elif, we add that condition to the list of conditions and we keep doing the same
 * if it's an else, we add the else block to the specified else_block property (since there can't be a condition) and we push the condition block node to the AST
 */
std::unique_ptr<cerne::Node> cerne::If(const cerne::blueprint_arguments& args) {
    auto& machine = args.machine;

    // disallow initalization in if blocks
    machine->no_init = true;

    auto condition_block = std::make_unique<cerne::ConditionBlock>(machine->peek().span); // temporarily set the span to the if token, we update this at the end
    bool should_end = false;

    // immediately get first condition (mandatory)
    auto first_condition = parse_condition(args, condition_block, true);
    if(!first_condition) return nullptr; // return if we fail to parse the first condition

    // do the same for every other possible elif and eventually else
    while(!should_end && machine->offset < machine->list.size()) {
        auto& token = machine->peek();

        if(token.type == TokenTypes::MNEMONIC) {
            mnemonic_cases(args, condition_block, &should_end, token);
            if(!should_end) continue; // if we didn't set should_end to true, we continue the loop to check for more mnemonics
        }

        // if it's not a mnemonic, it's just part of another statement, so we break out of the loop and construct the span for the condition block
        should_end = true;
    }

    condition_block->span = Span{
        condition_block->span.line,
        condition_block->span.col,
        condition_block->span.offset,
        (machine->peek(-1).span.offset + machine->peek(-1).span.length) - condition_block->span.offset
    };

    machine->no_init = false;

    return condition_block;
}